# -*- coding: utf-8 -*-
"""Reverse a Number (Without String Conversion) v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BW5w6gzcooEsuRDbHDkDfubME70zymeA
"""

num = int(input("enter the number:"))
revers = 0
input_digit = len(str(num))
print('The no of digints in input:', input_digit)
while num >0:
  last_num = num %10
  revers = revers *10 + last_num
  num = num//10
output_digit = len(str(revers))
print('The no of digints in output:',output_digit)
difference = input_digit - output_digit
print('The difference is:',difference)

print('0' * difference + str(revers))